// <auto-generated />
using ContractorFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322144205_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("ContractorFinder.Models.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractorCoverPhoto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorIndustry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorReview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContractorId");

                    b.ToTable("Contractors");
                });
#pragma warning restore 612, 618
        }
    }
}
